// @codekit-append functionBlocks/helpPassword.js
// @codekit-append functionBlocks/validate.js
// @codekit-append functionBlocks/showPopup.js
// @codekit-append functionBlocks/adminLogin.js
// @codekit-append functionBlocks/handleIndex.js
// @codekit-append functionBlocks/handleProjectEdit.js
// @codekit-append functionBlocks/modalControl.js
// @codekit-append functionBlocks/textareaResize.js
// @codekit-append functionBlocks/editBlogPost.js
// @codekit-append functionBlocks/addBlogPost.js
// @codekit-append functionBlocks/blog.js
// @codekit-append functionBlocks/headerControl.js
// @codekit-append functionBlocks/carousel.js
// @codekit-append functionBlocks/handleSubscribers.js
// @codekit-append functionBlocks/sendNewsletter.js
// @codekit-append functionBlocks/deleteSubscriber.js
// @codekit-append functionBlocks/createSubscriber.js
// @codekit-append functionBlocks/editTestimon.js
// @codekit-append functionBlocks/handleLoader.js
// @codekit-append functionBlocks/smoothScroll.js
// @codekit-append functionBlocks/handleCollapsibleButton.js
// @codekit-append functionBlocks/handleMobileMenu.js
